  language: node_js

notifications: # set notification options
  email:
    recipients:
      - russellTravisBuilds@marktareshawty.com
      
sudo: false

node_js:
  - "4.1"

services:
  - postgresql
  
before_script:
  - psql -c 'create database spending_tracker_development;' -U postgres
  - node db/testSetup.js
