language: node_js

notifications: # set notification options
  email: false
      
sudo: false

node_js:
  - "4.1"

services:
  - postgresql
  - redis-server
  
before_script:
  - psql -c 'create database spending_tracker_development;' -U postgres
  - node db/setup.js
