#!/bin/sh

# script/server: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.

set -e

cd "$(dirname "$0")/.."

redis-server --daemonize yes
node index.js

